#ifndef __SIMPAD2_GPIO_H__
#define __SIMPAD2_GPIO_H__

#define KEY_FUNCTION 		IMX_GPIO_NR(1, 4)
#define GPIO_CAP_TOUCH_RST	IMX_GPIO_NR(4, 10)
#define GPIO_AUX_5V_EN		IMX_GPIO_NR(4, 9)
#define GPIO_CHARGER_NCE	IMX_GPIO_NR(4, 14)
#define GPIO_TOUCH_IRQ 		IMX_GPIO_NR(7, 13)
#define GPIO_ADAPTER_N		IMX_GPIO_NR(4, 5)
#define GPIO_WL_VDDIO_EN	IMX_GPIO_NR(6, 11)
#define GPIO_BT_WAKE		IMX_GPIO_NR(6, 8)
#define GPIO_WL_REG_ON		IMX_GPIO_NR(2, 3)
#define GPIO_BT_REG_ON		IMX_GPIO_NR(2, 4)
#define GPIO_RECOVERY_SWITCH	IMX_GPIO_NR(5, 2)
#define GPIO_SPI_NOR_WP 	IMX_GPIO_NR(3, 20)
#define GPIO_CHARGER_ISET	IMX_GPIO_NR(3, 23)
#define GPIO_WL_BAT_PWR_EN	IMX_GPIO_NR(3, 26)
#define GPIO_HW_SETTING0	IMX_GPIO_NR(3, 27)
#define GPIO_HW_SETTING1	IMX_GPIO_NR(3, 28)
#define GPIO_HW_SETTING2	IMX_GPIO_NR(4, 11)
#define GPIO_PWR_BTN		IMX_GPIO_NR(3, 29)
#define GPIO_DDR_SETTING	IMX_GPIO_NR(3, 31)
#define GPIO_LED_R			IMX_GPIO_NR(1, 18)
#define GPIO_LED_G			IMX_GPIO_NR(1, 20)
#define GPIO_LED_B			IMX_GPIO_NR(1, 16)

#define SPI_CS_GPIO 		IMX_GPIO_NR(3, 19)

#define GPIO_LCD_EN			IMX_GPIO_NR(1, 30)
#define GPIO_BL_EN			IMX_GPIO_NR(4, 8)
#define GPIO_LCD_LR			IMX_GPIO_NR(1, 7)
#define GPIO_LCD_UD			IMX_GPIO_NR(1, 8)
#define GPIO_VIBRA			IMX_GPIO_NR(1, 19)

#define GPIO_USB_PWR        IMX_GPIO_NR(3, 22)
/* PCU */
#define GPIO_PCU_CLR			IMX_GPIO_NR(4, 15)
#define GPIO_PCU_START_ADAPTER	IMX_GPIO_NR(5, 16)
#define GPIO_PCU_START_KEY		IMX_GPIO_NR(5, 17)

#endif
