#ifndef __SIMPAD2_GPIO_H__
#define __SIMPAD2_GPIO_H__

#define GPIO_AUX_12V_EN	 	IMX_GPIO_NR(4, 8)
#define GPIO_AUX_5V_EN		IMX_GPIO_NR(4, 9)

#define GPIO_CHARGER2_CE_N	IMX_GPIO_NR(4, 10)
#define GPIO_VCC5_EN_R		IMX_GPIO_NR(4, 11)
#define GPIO_CHARGER_CE_N	IMX_GPIO_NR(4, 14)
#define GPIO_HEADPHONE_DET	IMX_GPIO_NR(1, 4)
#define GPIO_SPK_SD_N		IMX_GPIO_NR(1, 5)
#define GPIO_LINE_IN_DET	IMX_GPIO_NR(1, 9)

#define GPIO_ADAPTER_N		IMX_GPIO_NR(4, 5)
#define GPIO_USB_H1_EN		IMX_GPIO_NR(1, 29)

#define GPIO_WL_VDDIO_EN	IMX_GPIO_NR(6, 11)
#define GPIO_BT_WAKE		IMX_GPIO_NR(6, 8)
#define GPIO_WL_REG_ON		IMX_GPIO_NR(2, 3)
#define GPIO_BT_REG_ON		IMX_GPIO_NR(2, 4)
#define GPIO_RECOVERY_SWITCH	IMX_GPIO_NR(5, 2)
#define GPIO_SPI_NOR_WP 	IMX_GPIO_NR(3, 20)
#define GPIO_WL_BAT_PWR_EN	IMX_GPIO_NR(3, 26)
#define GPIO_HW_SETTING0	IMX_GPIO_NR(3, 27)
#define GPIO_HW_SETTING1	IMX_GPIO_NR(3, 28)
#define GPIO_HW_SETTING2	IMX_GPIO_NR(4, 10)
#define GPIO_PWR_BTN		IMX_GPIO_NR(3, 29)
#define GPIO_LED_R			IMX_GPIO_NR(1, 18)
#define GPIO_LED_G			IMX_GPIO_NR(1, 20)
#define GPIO_LED_B			IMX_GPIO_NR(1, 16)
#define SPI_CS_GPIO 		IMX_GPIO_NR(3, 19)

#define GPIO_AC5W_SD_N		IMX_GPIO_NR(4, 25)
#define GPIO_MCU_RST		IMX_GPIO_NR(4, 26)
#define GPIO_MCU_BOOT0		IMX_GPIO_NR(4, 27)
#define GPIO_MCU_BOOT1		IMX_GPIO_NR(4, 28)
#define GPIO_BOOST_12V_EN	IMX_GPIO_NR(4, 29)
#define GPIO_BAT1_DET_N		IMX_GPIO_NR(4, 31)
#define GPIO_BAT2_DET_N		IMX_GPIO_NR(5, 5)
#define GPIO_WIFI_LED_G		IMX_GPIO_NR(5, 6)
#define GPIO_WIFI_LED_B		IMX_GPIO_NR(5, 7)
#define GPIO_WIFI_LED_R		IMX_GPIO_NR(5, 8)
#define GPIO_PWM3			IMX_GPIO_NR(1, 17)
#define GPIO_PWM2			IMX_GPIO_NR(1, 19)
#define GPIO_PWM1			IMX_GPIO_NR(1, 21)
/* PMU */
#define GPIO_PMU_RST_N		IMX_GPIO_NR(5, 13)
#define GPIO_PMU_SPI_CS		IMX_GPIO_NR(5, 12)
#define GPIO_PMU_STATUS		IMX_GPIO_NR(5, 17)

#endif
