#ifndef __SIMPAD2_PINS_H__
#define __SIMPAD2_PINS_H__

static iomux_v3_cfg_t const uart1_pads[] = {
	MX6_PAD_CSI0_DAT10__UART1_TX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX6_PAD_CSI0_DAT11__UART1_RX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL),
};

static iomux_v3_cfg_t const uart4_pads[] = {
	MX6_PAD_CSI0_DAT12__UART4_TX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX6_PAD_CSI0_DAT13__UART4_RX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX6_PAD_CSI0_DAT16__UART4_RTS_B | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX6_PAD_CSI0_DAT17__UART4_CTS_B | MUX_PAD_CTRL(UART_PAD_CTRL),
};

static iomux_v3_cfg_t const uart5_pads[] = {
	MX6_PAD_CSI0_DAT14__UART5_TX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX6_PAD_CSI0_DAT15__UART5_RX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX6_PAD_CSI0_DAT18__UART5_RTS_B | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX6_PAD_CSI0_DAT19__UART5_CTS_B | MUX_PAD_CTRL(UART_PAD_CTRL),
};

static iomux_v3_cfg_t const enet_pads[] = {
	MX6_PAD_ENET_MDIO__ENET_MDIO		| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_ENET_MDC__ENET_MDC		| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_RGMII_TXC__RGMII_TXC	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_RGMII_TD0__RGMII_TD0	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_RGMII_TD1__RGMII_TD1	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_RGMII_TD2__RGMII_TD2	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_RGMII_TD3__RGMII_TD3	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_RGMII_TX_CTL__RGMII_TX_CTL	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_ENET_REF_CLK__ENET_TX_CLK	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_RGMII_RXC__RGMII_RXC	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_RGMII_RD0__RGMII_RD0	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_RGMII_RD1__RGMII_RD1	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_RGMII_RD2__RGMII_RD2	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_RGMII_RD3__RGMII_RD3	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_RGMII_RX_CTL__RGMII_RX_CTL	| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX6_PAD_ENET_RXD1__GPIO1_IO26	| MUX_PAD_CTRL(NO_PAD_CTRL),
	/* AR8031 PHY Reset */
	MX6_PAD_ENET_CRS_DV__GPIO1_IO25		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* Phy reset (low) */
};


static iomux_v3_cfg_t const usdhc2_pads[] = {
	MX6_PAD_SD2_CLK__SD2_CLK   | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD2_CMD__SD2_CMD   | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD2_DAT0__SD2_DATA0 | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD2_DAT1__SD2_DATA1 | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD2_DAT2__SD2_DATA2 | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD2_DAT3__SD2_DATA3 | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_NANDF_D2__GPIO2_IO02 | MUX_PAD_CTRL(NO_PAD_CTRL),	/* Card Detect */
	MX6_PAD_NANDF_D1__GPIO2_IO01 | MUX_PAD_CTRL(NO_PAD_CTRL),	/* Write Protect */
};

static iomux_v3_cfg_t const usdhc4_pads[] = {
	MX6_PAD_SD4_CLK__SD4_CLK   | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD4_CMD__SD4_CMD   | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD4_DAT0__SD4_DATA0 | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD4_DAT1__SD4_DATA1 | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD4_DAT2__SD4_DATA2 | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD4_DAT3__SD4_DATA3 | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD4_DAT4__SD4_DATA4 | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD4_DAT5__SD4_DATA5 | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD4_DAT6__SD4_DATA6 | MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX6_PAD_SD4_DAT7__SD4_DATA7 | MUX_PAD_CTRL(USDHC_PAD_CTRL),
};


static iomux_v3_cfg_t const usb_otg_pads[] = {
	MX6_PAD_EIM_D22__USB_OTG_PWR 	| MUX_PAD_CTRL(NO_PAD_CTRL),
	MX6_PAD_EIM_D21__USB_OTG_OC 	| MUX_PAD_CTRL(NO_PAD_CTRL),
	MX6_PAD_ENET_RX_ER__USB_OTG_ID 	| MUX_PAD_CTRL(REGINP_PAD_CTRL),
};

static iomux_v3_cfg_t const usb_pads[] = {
	MX6_PAD_EIM_D31__GPIO3_IO31 	| MUX_PAD_CTRL(REGINP_PAD_CTRL),	/* H1 OC */
	MX6_PAD_ENET_TXD1__GPIO1_IO29 	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* H1 PWR Enable */
};

static iomux_v3_cfg_t const other_pads[] = {
	MX6_PAD_NANDF_CLE__GPIO6_IO07	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* GP--BT_HOST_WAKE */
	MX6_PAD_GPIO_4__GPIO1_IO04		| MUX_PAD_CTRL(REGINP_PAD_CTRL),/* Function key (active low) */
	MX6_PAD_KEY_COL2__GPIO4_IO10	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* Touch reset (low)	*/
	MX6_PAD_KEY_ROW1__GPIO4_IO09	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* AUX_5V_EN */
	MX6_PAD_KEY_COL4__GPIO4_IO14	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* GP--Charger_nCE */
	MX6_PAD_GPIO_0__ASRC_EXT_CLK	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* External audio clk */
	MX6_PAD_GPIO_1__WDOG2_B			| MUX_PAD_CTRL(NO_PAD_CTRL),
	MX6_PAD_GPIO_9__GPIO1_IO09		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* GP--HP_DET */
	MX6_PAD_GPIO_18__GPIO7_IO13		| MUX_PAD_CTRL(PAD_CTL_ODE | PAD_CTL_PUS_100K_UP | PAD_CTL_PUE),	/* GP--CTP_nINT (touch interrupt */
	MX6_PAD_GPIO_19__GPIO4_IO05		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* DC_IN_nFLG (adapter detect) */
	MX6_PAD_NANDF_CS0__GPIO6_IO11	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* GP--WL_VDDIO_EN */
	MX6_PAD_NANDF_ALE__GPIO6_IO08	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* GP--BT_WAKE */
	MX6_PAD_NANDF_RB0__GPIO6_IO10	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* PMIC_INT_B */
	MX6_PAD_NANDF_D1__GPIO2_IO01	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* ACCL_INT_IN */
	MX6_PAD_NANDF_D3__GPIO2_IO03	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* WL_REG_ON (WiFI power) */
	MX6_PAD_NANDF_D4__GPIO2_IO04	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* BT_REG_ON (Bluetooth power) */
	MX6_PAD_NANDF_D5__GPIO2_IO05	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* WL_IRQ (WiFI interrupt */
	MX6_PAD_NANDF_D6__GPIO2_IO06	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* GP--WL_HOST_WAKE */
	MX6_PAD_NANDF_D7__GPIO2_IO07	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* GP--WL_DEV_WAKE */
	MX6_PAD_EIM_OE__ECSPI2_MISO		| MUX_PAD_CTRL(SPI_PAD_CTRL),	/* ECSPI2_MISO */
	MX6_PAD_EIM_CS0__ECSPI2_SCLK	| MUX_PAD_CTRL(SPI_PAD_CTRL),
	MX6_PAD_EIM_CS1__ECSPI2_MOSI	| MUX_PAD_CTRL(SPI_PAD_CTRL),
	MX6_PAD_EIM_A25__GPIO5_IO02		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* Recovery_setting (control boot) */
	MX6_PAD_EIM_D20__GPIO3_IO20		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* GP--nWP--flash (SPI flash WP) */
	MX6_PAD_EIM_D23__GPIO3_IO23		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* GP--CHarger_ISET */
	MX6_PAD_EIM_D26__GPIO3_IO26		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* GP--WL_BAT_PWR_EN */
	MX6_PAD_EIM_D27__GPIO3_IO27		| MUX_PAD_CTRL(REGINP_PAD_CTRL),	/* HW_Setting_0 */
	MX6_PAD_EIM_D28__GPIO3_IO28		| MUX_PAD_CTRL(REGINP_PAD_CTRL),	/* HW_Setting_1 */
	MX6_PAD_EIM_D29__GPIO3_IO29		| MUX_PAD_CTRL(REGINP_PAD_CTRL),	/* PPWR_BTN_SNS */
	MX6_PAD_EIM_D31__GPIO3_IO31		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* DDR_Setting */
	MX6_PAD_CSI0_DAT4__AUD3_TXC		| MUX_PAD_CTRL(NO_PAD_CTRL),
	MX6_PAD_CSI0_DAT5__AUD3_TXD		| MUX_PAD_CTRL(NO_PAD_CTRL),
	MX6_PAD_CSI0_DAT6__AUD3_TXFS	| MUX_PAD_CTRL(NO_PAD_CTRL),
	MX6_PAD_CSI0_DAT7__AUD3_RXD		| MUX_PAD_CTRL(NO_PAD_CTRL),
	MX6_PAD_CSI0_DAT14__UART5_TX_DATA | MUX_PAD_CTRL(NO_PAD_CTRL),
	MX6_PAD_CSI0_DAT15__UART5_RX_DATA | MUX_PAD_CTRL(NO_PAD_CTRL),
	MX6_PAD_CSI0_DAT18__UART5_CTS_B	| MUX_PAD_CTRL(NO_PAD_CTRL),
	MX6_PAD_CSI0_DAT19__UART5_RTS_B	| MUX_PAD_CTRL(NO_PAD_CTRL),
	MX6_PAD_SD1_CMD__GPIO1_IO18		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* LED_R_Status--CPU */
	MX6_PAD_SD1_CLK__GPIO1_IO20		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* LED_G_Status--CPU */
	MX6_PAD_SD1_DAT0__GPIO1_IO16	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* LED_B_Status--CPU */
	MX6_PAD_SD1_DAT2__GPIO1_IO19	| MUX_PAD_CTRL(NO_PAD_CTRL),	/* PWM2--CPU (vib) */
	MX6_PAD_SD1_DAT3__PWM1_OUT		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* PWM_DISP0_BL (backlight) */
	MX6_PAD_SD2_DAT0__AUD4_RXD		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* Bluetooth PCM */
	MX6_PAD_SD2_DAT1__AUD4_TXFS		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* Bluetooth PCM */
	MX6_PAD_SD2_DAT2__AUD4_TXD		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* Bluetooth PCM */
	MX6_PAD_SD2_DAT3__AUD4_TXC		| MUX_PAD_CTRL(NO_PAD_CTRL),	/* Bluetooth PCM */
};

static struct i2c_pads_info i2c_pad_info0 = {
		.scl = {
			.i2c_mode = MX6_PAD_CSI0_DAT9__I2C1_SCL | MUX_PAD_CTRL(I2C_PAD_CTRL),
			.gpio_mode = MX6_PAD_CSI0_DAT9__GPIO5_IO27 | MUX_PAD_CTRL(I2C_PAD_CTRL),
			.gp = IMX_GPIO_NR(5, 27)
		},
		.sda = {
			.i2c_mode = MX6_PAD_CSI0_DAT8__I2C1_SDA | MUX_PAD_CTRL(I2C_PAD_CTRL),
			.gpio_mode = MX6_PAD_CSI0_DAT8__GPIO5_IO26 | MUX_PAD_CTRL(I2C_PAD_CTRL),
			.gp = IMX_GPIO_NR(5, 26)
		}
	};

static struct i2c_pads_info i2c_pad_info1 = {
	.scl = {
		.i2c_mode = MX6_PAD_KEY_COL3__I2C2_SCL | MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX6_PAD_KEY_COL3__GPIO4_IO12 | MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 12)
	},
	.sda = {
		.i2c_mode = MX6_PAD_KEY_ROW3__I2C2_SDA | MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX6_PAD_KEY_ROW3__GPIO4_IO13 | MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 13)
	}
};

static struct i2c_pads_info i2c_pad_info2 = {
	.scl = {
		.i2c_mode = MX6_PAD_GPIO_3__I2C3_SCL | MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX6_PAD_GPIO_3__GPIO1_IO03 | MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(1, 3)
	},
	.sda = {
		.i2c_mode = MX6_PAD_GPIO_16__I2C3_SDA | MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX6_PAD_GPIO_16__GPIO7_IO11 | MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(1, 6)
	}
};

static iomux_v3_cfg_t i2c_pads[] = {
	MX6_PAD_CSI0_DAT9__I2C1_SCL | MUX_PAD_CTRL(I2C_PAD_CTRL),
	MX6_PAD_CSI0_DAT8__I2C1_SDA | MUX_PAD_CTRL(I2C_PAD_CTRL),
	MX6_PAD_KEY_COL3__I2C2_SCL 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
	MX6_PAD_KEY_ROW3__I2C2_SDA 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
	MX6_PAD_GPIO_3__I2C3_SCL | MUX_PAD_CTRL(I2C_PAD_CTRL),
	MX6_PAD_GPIO_16__I2C3_SDA | MUX_PAD_CTRL(I2C_PAD_CTRL),
};
#endif

