#ifndef __MXXF1_GPIO_H__
#define __MXXF1_GPIO_H__

#define GPIO_AUX_5V IMX_GPIO_NR(6, 10)
#define GPIO_PCIE_RST_N IMX_GPIO_NR(7, 12)
#define GPIO_EEPROM_WP	IMX_GPIO_NR(1, 5)
#define GPIO_SPI_NOR_WP	IMX_GPIO_NR(6, 11)
#define GPIO_LAN2_EE_WP	IMX_GPIO_NR(6, 14)
#define GPIO_CAP_TOUCH_RST	IMX_GPIO_NR(6, 16)
#define GPIO_CAP_TOUCH_PWR	IMX_GPIO_NR(1, 4)
#define GPIO_LCD_EN	IMX_GPIO_NR(6, 15)
#define GPIO_BL_EN	IMX_GPIO_NR(1, 2)
#define GPIO_BL_PWM	IMX_GPIO_NR(1, 9)
#define GPIO_FAN_EN IMX_GPIO_NR(1, 18)
#define GPIO_BUZ_INT_EN IMX_GPIO_NR(1, 17)
#define GPIO_BUZ_EXT_EN IMX_GPIO_NR(1, 19)

#define GPIO_USB_H1_EN	IMX_GPIO_NR(1, 29)
#define GPIO_USBP0_EN	IMX_GPIO_NR(3, 28)
#define GPIO_USBP1_EN	IMX_GPIO_NR(2, 3)
#define GPIO_USBP2_EN	IMX_GPIO_NR(2, 7)
#define GPIO_USBP3_EN	IMX_GPIO_NR(6, 9)
#define GPIO_LVDS_ROTATE IMX_GPIO_NR(7, 11)

#define GPIO_DIMM_DN IMX_GPIO_NR(4, 6)
#define GPIO_DIMM_UP IMX_GPIO_NR(4, 7)

#define GPIO_TOUCH_IRQ IMX_GPIO_NR(6, 8)
#define USDHC3_CD_GPIO	IMX_GPIO_NR(2, 0)

#define GPIO_HW_REV0 IMX_GPIO_NR(1, 15)
#define GPIO_HW_REV1 IMX_GPIO_NR(1, 14)
#define GPIO_HW_REV2 IMX_GPIO_NR(1, 13)
#define GPIO_HW_REV3 IMX_GPIO_NR(1, 12)

#define GPIO_FEC_PHY_NRST IMX_GPIO_NR(1, 25)

#endif
