#ifndef __SIMPAD2_GPIO_H__
#define __SIMPAD2_GPIO_H__

#define GPIO_WL_VDDIO_EN	IMX_GPIO_NR(6, 11)
#define GPIO_BT_WAKE		IMX_GPIO_NR(6, 8)
#define GPIO_WL_REG_ON		IMX_GPIO_NR(2, 3)
#define GPIO_BT_REG_ON		IMX_GPIO_NR(2, 4)
#define GPIO_SPI_NOR_WP 	IMX_GPIO_NR(3, 20)
#define GPIO_WL_BAT_PWR_EN	IMX_GPIO_NR(3, 26)
#define GPIO_HW_SETTING0	IMX_GPIO_NR(4, 21)
#define GPIO_HW_SETTING1	IMX_GPIO_NR(4, 22)
#define GPIO_HW_SETTING2	IMX_GPIO_NR(4, 23)
#define GPIO_PWR_BTN		IMX_GPIO_NR(3, 29)
#define GPIO_LED_R			IMX_GPIO_NR(1, 17)
#define GPIO_LED_G			IMX_GPIO_NR(1, 19)
#define GPIO_LED_B			IMX_GPIO_NR(1, 21)
#define SPI_CS_GPIO 		IMX_GPIO_NR(3, 19)


#endif
