
// GPIO
#if CONFIG_HW_VERSION == 0
#define GPIO_NET_12V_EN		IMX_GPIO_NR(1, 7)
#define GPIO_NET_3V35_EN	IMX_GPIO_NR(1, 18)
#define GPIO_FPGA_CS_N			IMX_GPIO_NR(5, 9)
#define GPIO_FPGA_CE_N			IMX_GPIO_NR(5, 12)
#endif

#if CONFIG_HW_VERSION > 0
#define GPIO_FPGA_CONFIG_INT_DONE	IMX_GPIO_NR(5, 11)
#define GPIO_FPGA_CONFIG_CRC_ERR	IMX_GPIO_NR(5, 12)
#endif

#define GPIO_LAN_3V3_EN		IMX_GPIO_NR(1, 20)

#define GPIO_LAN_RESETn			IMX_GPIO_NR(3, 23)
#define GPIO_LAN_INTRn			IMX_GPIO_NR(3, 29)
#define GPIO_LAN_LINK_STATUS1	IMX_GPIO_NR(3, 30)
#define GPIO_LAN_LINK_STATUS2	IMX_GPIO_NR(3, 31)

#define GPIO_FPGA_12V_EN		IMX_GPIO_NR(4, 8)
#define GPIO_FPGA_3V3_EN		IMX_GPIO_NR(4, 9)
#define GPIO_FPGA_2V5_EN		IMX_GPIO_NR(4, 10)
#define GPIO_FPGA_1V1_EN		IMX_GPIO_NR(4, 11)

#define GPIO_ADM_BUS_VMB_TX_EN	IMX_GPIO_NR(5, 5)
#define GPIO_ADM_BUS_VMB_RX_EN	IMX_GPIO_NR(5, 6)
#define GPIO_ADM_BUS_PMB_TX_EN	IMX_GPIO_NR(5, 7)
#define GPIO_ADM_BUS_PMB_RX_EN	IMX_GPIO_NR(5, 8)

#define GPIO_FPGA_DONE			IMX_GPIO_NR(5, 14)
#define GPIO_FPGA_STATUSn		IMX_GPIO_NR(5, 15)
#define GPIO_FPGA_CONFIGn		IMX_GPIO_NR(5, 16)
#define GPIO_MAIN_3V35_PGOOD	IMX_GPIO_NR(5, 17)
#define GPIO_PCIE_RESETn		IMX_GPIO_NR(5, 21)
#define GPIO_SATA_DA_DSS		IMX_GPIO_NR(5, 22)
#define GPIO_SATA_DP			IMX_GPIO_NR(5, 23)

#undef BIT_BANG_FPGA
